var simplemaps_usmap_mapdata = {
  main_settings: {
    width: "responsive",
    background_color: "#FFFFFF",
    background_transparent: "yes",
    popups: "detect",
    state_color: "#88A4BC",
    state_hover_color: "#3B729F",
    border_size: 1.5,
    border_color: "#ffffff",
    all_states_inactive: "no",
    all_states_zoomable: "no",
    div: "map",
    auto_load: "yes",
    url_new_tab: "yes",
  },
  state_specific: {
    AL: { name: "Alabama", url: "https://www.alherpsociety.org/" },
    AK: { name: "Alaska", url: "http://www.adfg.alaska.gov/index.cfm?adfg=amphibians.main" },
    AZ: { name: "Arizona", url: "https://www.azherp.com/" },
    AR: { name: "Arkansas", url: "https://arkansasherpsociety.org/" },
    CA: { name: "California", url: "https://www.californiaherps.com/" },
    CO: { name: "Colorado", url: "https://www.coloherps.org/" },
    CT: { name: "Connecticut", url: "https://portal.ct.gov/DEEP/Wildlife/Fact-Sheets/Reptiles" },
    DE: { name: "Delaware", url: "https://dnrec.alpha.delaware.gov/fish-wildlife/conservation/amphibians-reptiles/" },
    FL: { name: "Florida", url: "https://www.floridamuseum.ufl.edu/herpetology/fl-snakes/" },
    GA: { name: "Georgia", url: "https://www.gareptilesociety.org/" },
    HI: { name: "Hawaii", url: "https://dlnr.hawaii.gov/wildlife/reptiles/" },
    ID: { name: "Idaho", url: "https://www.idahohs.org/" },
    IL: { name: "Illinois", url: "https://www.chicagoherp.org/" },
    IN: { name: "Indiana", url: "https://www.hoosierherpsoc.org/" },
    IA: { name: "Iowa", url: "https://www.iowaherps.com/" },
    KS: { name: "Kansas", url: "https://ksherp.com/" },
    KY: { name: "Kentucky", url: "https://www.kyherpsoc.org/" },
    LA: { name: "Louisiana", url: "https://www.wlf.louisiana.gov/page/reptiles" },
    ME: { name: "Maine", url: "https://www.maine.gov/ifw/wildlife/species/reptiles/index.html" },
    MD: { name: "Maryland", url: "https://www.marylandnature.org/get-involved/affiliated-societies/maryland-herpetological-society/" },
    MA: { name: "Massachusetts", url: "https://www.massaudubon.org/learn/nature-wildlife/reptiles-amphibians" },
    MI: { name: "Michigan", url: "https://michherp.org/" },
    MN: { name: "Minnesota", url: "https://mnherpsoc.org/" },
    MS: { name: "Mississippi", url: "https://www.mississippientomologicalmuseum.org.msstate.edu/mississippiherps/index.php" },
    MO: { name: "Missouri", url: "https://mha.moherp.org/" },
    MT: { name: "Montana", url: "https://mtnhp.org/SpeciesOfConcern/?AorP=a" },
    NE: { name: "Nebraska", url: "https://www.nebraskaherpetology.org/" },
    NV: { name: "Nevada", url: "http://www.ndow.org/Species/Reptiles/" },
    NH: { name: "New Hampshire", url: "https://www.wildlife.state.nh.us/wildlife/profiles/reptiles.html" },
    NJ: { name: "New Jersey", url: "https://herpetologicalassociates.com/" },
    NM: { name: "New Mexico", url: "https://www.nmherpsociety.org/" },
    NY: { name: "New York", url: "https://nyherp.org/" },
    NC: { name: "North Carolina", url: "https://ncherps.org/" },
    ND: { name: "North Dakota", url: "https://gf.nd.gov/wildlife/id/reptiles" },
    OH: { name: "Ohio", url: "http://wildlife.ohiodnr.gov/species-and-habitats/reptiles" },
    OK: { name: "Oklahoma", url: "https://www.wildlifedepartment.com/wildlife/field-guide/reptiles" },
    OR: { name: "Oregon", url: "https://www.dfw.state.or.us/wildlife/living_with/snakes.asp" },
    PA: { name: "Pennsylvania", url: "https://www.machac.org/" },
    RI: { name: "Rhode Island", url: "https://www.dem.ri.gov/natural-resources-bureau/fish-wildlife/ri-herpetofauna" },
    SC: { name: "South Carolina", url: "https://www.dnr.sc.gov/wildlife/herps/snakes.html" },
    SD: { name: "South Dakota", url: "https://gfp.sd.gov/reptiles/" },
    TN: { name: "Tennessee", url: "https://tnherpsociety.org/" },
    TX: { name: "Texas", url: "https://www.texasherp.org/" },
    UT: { name: "Utah", url: "https://wildlife.utah.gov/utah-wildlife-guide/reptiles.html" },
    VT: { name: "Vermont", url: "https://vtfishandwildlife.com/conserve/animal-species/reptiles-and-amphibians" },
    VA: { name: "Virginia", url: "https://www.virginiaherpetologicalsociety.com/" },
    WA: { name: "Washington", url: "https://wdfw.wa.gov/species-habitats/living/snakes" },
    WV: { name: "West Virginia", url: "https://www.wvherpsociety.org/" },
    WI: { name: "Wisconsin", url: "https://dnr.wisconsin.gov/topic/WildlifeHabitat/Herps.html" },
    WY: { name: "Wyoming", url: "https://wgfd.wyo.gov/Wildlife-in-Wyoming/More-Wildlife/Reptiles-and-Amphibians" },
    DC: { name: "District of Columbia", url: "https://nationalzoo.si.edu/animals/reptiles-and-amphibians" },
    GU: { name: "Guam", url: "https://www.guam.nfwf.org/" }
  }
};
