var simplemaps_usmap_mapdata = {
  main_settings: {
    width: "responsive",
    background_color: "#FFFFFF",
    background_transparent: "yes",
    popups: "detect",
    state_color: "#88A4BC",
    state_hover_color: "#3B729F",
    border_size: 1.5,
    border_color: "#ffffff",
    all_states_inactive: "no",
    all_states_zoomable: "no",
    div: "map",
    auto_load: "yes",
    url_new_tab: "yes",
  },
  state_specific: {
    AL: { name: "Alabama", url: "https://www.outdooralabama.com/reptiles/snakes" },
    AK: { name: "Alaska", url: "https://a-z-animals.com/blog/snakes-in-alaska/" },
    AZ: { name: "Arizona", url: "https://azstateparks.com/arizona-snakes" },
    AR: { name: "Arkansas", url: "https://herpsofarkansas.com/reptiles/snakes/" },
    CA: { name: "California", url: "https://www.californiaherps.com/info/findsnakes.html/" },
    CO: { name: "Colorado", url: "https://www.coloherps.org/" },
    CT: { name: "Connecticut", url: "https://portal.ct.gov/deep/wildlife/learn-about-wildlife/snakes-of-connecticut" },
    DE: { name: "Delaware", url: "https://dnrec.delaware.gov/outdoor-delaware/snakes-to-watch-out-for/" },
    FL: { name: "Florida", url: "https://www.floridamuseum.ufl.edu/herpetology/fl-snakes/" },
    GA: { name: "Georgia", url: "https://srelherp.uga.edu/snakes/" },
    HI: { name: "Hawaii", url: "https://maalaea.com/are-there-snakes-in-hawaii/" },
    ID: { name: "Idaho", url: "https://a-z-animals.com/animals/snake/snake-facts/snakes-found-in-idaho/" },
    IL: { name: "Illinois", url: "https://wildlifeillinois.org/identify-wildlife/snakes/" },
    IN: { name: "Indiana", url: "https://www.hoosierherpsociety.org/snakes" },
    IA: { name: "Iowa", url: "https://www.iowaherps.com/group/snakes" },
    KS: { name: "Kansas", url: "https://kysnakes.ca.uky.edu/KY_snakes" },
    KY: { name: "Kentucky", url: "https://fw.ky.gov/Wildlife/Documents/kysnakebook.pdf" },
    LA: { name: "Louisiana", url: "https://www.inaturalist.org/guides/11675" },
    ME: { name: "Maine", url: "https://www.snakesnap.co/snakes-of-maine" },
    MD: { name: "Maryland", url: "https://dnr.maryland.gov/wildlife/Pages/plants_wildlife/herps/Fieldguide_OrderSquamata.aspx" },
    MA: { name: "Massachusetts", url: "https://www.mass.gov/info-details/snakes-of-massachusetts" },
    MI: { name: "Michigan", url: "https://www.michigan.gov/dnr/education/michigan-species/reptiles/snakes" },
    MN: { name: "Minnesota", url: "https://www.mnherps.com/group/snakes" },
    MS: { name: "Mississippi", url: "https://msherps.com/snakes/" },
    MO: { name: "Missouri", url: "https://mdc.mo.gov/sites/default/files/mo_nature/downloads/page/MissouriSnakes.pdf" },
    MT: { name: "Montana", url: "https://www.snakesnap.co/snakes-of-montana" },
    NE: { name: "Nebraska", url: "https://outdoornebraska.gov/learn/nebraska-wildlife/nebraska-animals/reptiles-and-amphibians/reptiles-of-nebraska/snakes-of-nebraska/" },
    NV: { name: "Nevada", url: "https://www.ndow.org/species-information/" },
    NH: { name: "New Hampshire", url: "https://www.wildlife.nh.gov/wildlife-and-habitat/nongame-and-endangered-species/reptiles-and-amphibians-new-hampshire/snakes" },
    NJ: { name: "New Jersey", url: "http://www.newjerseysnakes.com/" },
    NM: { name: "New Mexico", url: "https://www.nmherpsociety.org/reptiles/snakes/index.html" },
    NY: { name: "New York", url: "https://www.esf.edu/eis/eis-snakes.php" },
    NC: { name: "North Carolina", url: "https://herpsofnc.org/snakes/" },
    ND: { name: "North Dakota", url: "https://www.ndherpatlas.org/group/snakes" },
    OH: { name: "Ohio", url: "https://dam.assets.ohio.gov/image/upload/ohiodnr.gov/documents/wildlife/backyard-wildlife/Pub%205354_Reptiles%20of%20Ohio%20Field%20Guide.pdf" },
    OK: { name: "Oklahoma", url: "https://www.snakesnap.co/snakes-of-oklahoma" },
    OR: { name: "Oregon", url: "https://www.dfw.state.or.us/wildlife/living_with/snakes.asp" },
    PA: { name: "Pennsylvania", url: "https://www.paherps.com/herps/snakes/" },
    RI: { name: "Rhode Island", url: "https://dem.ri.gov/sites/g/files/xkgbur861/files/programs/bnatres/fishwild/pdf/snake.pdf" },
    SC: { name: "South Carolina", url: "https://srelherp.uga.edu/snakes/" },
    SD: { name: "South Dakota", url: "https://www.sdherps.org/group/snakes" },
    TN: { name: "Tennessee", url: "https://www.tn.gov/twra/wildlife/reptiles/snakes.html" },
    TX: { name: "Texas", url: "https://tpwd.texas.gov/education/hunter-education/online-course/preparation-and-survival/snakes" },
    UT: { name: "Utah", url: "https://reptilesofutah.com/snakes-of-utah/" },
    VT: { name: "Vermont", url: "https://vtfishandwildlife.com/conserve/conservation-planning/animal-inventory/reptiles-and-amphibians/snakes-of-vermont" },
    VA: { name: "Virginia", url: "https://www.virginiaherpetologicalsociety.com/reptiles/snakes/index.html" },
    WA: { name: "Washington", url: "https://wdfw.wa.gov/species-habitats/living/snakes" },
    WV: { name: "West Virginia", url: "https://www.wvherpsociety.org/snakes" },
    WI: { name: "Wisconsin", url: "https://dnr.wisconsin.gov/topic/WildlifeHabitat/Herps" },
    WY: { name: "Wyoming", url: "https://www.snakesnap.co/snakes-of-wyoming" },
    DC: { name: "District of Columbia", url: "http://www.washingtondcsnakes.com/" },
    GU: { name: "Guam", url: "https://www.guam.nfwf.org/" }
  }
};
